import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layouts/Navbar";
import Sidebar from "@/components/layouts/Sidebar";
import localFont from "next/font/local";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin-ext"],
});

const arabic = localFont({
  src: "./arabic-font.ttf",
  display: "swap",
  variable: "--arabic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${arabic.variable}`}>
        <Navbar />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
